const COLOR_DARK_SLATE_GRAY = "#335C67";
const COLOR_BLUE_MUNSSEL = "#4A8696";
const COLOR_VANILLA = "#FFF3B0";
const COLOR_HUNYADI_YELLOW = "#E09F3E";
const COLOR_AUBURN = "#9E2A2B";
const COLOR_CHOCOLATE_COSMOS = "#540B0E";

export {
    COLOR_AUBURN,
    COLOR_BLUE_MUNSSEL,
    COLOR_CHOCOLATE_COSMOS,
    COLOR_DARK_SLATE_GRAY,
    COLOR_HUNYADI_YELLOW,
    COLOR_VANILLA,
};
